default: &DEFAULT
  branch: master
  ssl: true
  scale: 1

environment: &ENV
  test:
    <<: *DEFAULT
    branch: any
    ssl: false
    fqdn: testing.hartware.fr
  preprod:
    <<: *DEFAULT
    branch: preprod
    fqdn: preprod.hartware.fr
  prod: &PROD
    <<: *DEFAULT

apps:
  blog:
    name: blog
    git: 
      url: git@bitbucket.org:ludwig778/blog.git
      type: bitbucket
    connect:
      method: "sock_file"
      arg: "/blog/tmp/socket"
      name: "unicorn.sock"
    environment:
      <<: *ENV
      prod:
        <<: *PROD
        fqdn: blog.hartware.fr

  django:
    name: django
    git: 
      url: git@github.com:ludwig778/django-demo.git
      type: github
    connect:
      method: "sock_file"
      arg: "/app/socket"
      name: "gunicorn.sock"
    environment:
      <<: *ENV
      prod:
        <<: *PROD
        fqdn: app.hartware.fr

  netcat:
    name: netcat
    git: 
      url: git@github.com:ludwig778/netcat_demo.git
      type: github
    connect:
      method: "port"
      arg: 8090
    environment:
      <<: *ENV
      prod:
        <<: *PROD
        fqdn: nc.hartware.fr
