default: &DEFAULT
  branch: master
  ssl: true
  scale: 1

environment: &ENV
  test: 
    <<: *DEFAULT
    branch: any
    ssl: false
    fqdn: test_app.hartware.fr
  preprod: 
    <<: *DEFAULT
    branch: preprod
    fqdn: preprod.hartware.fr
  prod: &PROD
    <<: *DEFAULT

apps:
  main:
    name: main
    git: git clone git@bitbucket.org:ludwig778/blog.git
    connect:
      method: "sock_file"
      arg: "/test.sock"
    environment: 
      <<: *ENV 
      prod:
        <<: *PROD
        fqdn: hartware.fr

  app:
    name: app
    git: 
    connect:
      method: "sock_file"
      arg: "/test.sock"
    environment:
      <<: *ENV
      prod:
        <<: *PROD
        fqdn: app.hartware.fr

  fake:
    name: fake
    git: 
    connect:
      method: "port"
      arg: 8080
    environment:
      <<: *ENV
      prod:
        <<: *PROD
        fqdn: fake.hartware.fr

